import express from "express";

const router = express.Router();

const titles = [
  "Matcha Crawl",
  "Sunset Walk Along Charles River",
  "Hidden Cafe Hunt",
  "North End Cannoli Tour",
  "Back Bay Bookstore Crawl",
  "Beacon Hill Photo Walk",
  "Seaport Food Truck Day",
  "Cambridge Coffee Shop Hop",
  "Somerville Vintage Shopping Day",
  "Fenway Game Day Experience",
  "Boston Public Garden Picnic",
  "Museum of Fine Arts Visit",
  "Harvard Yard Exploration",
  "MIT Campus Walk",
  "Boston Common Chill Day",
  "Late Night Chinatown Eats",
  "Ice Cream Crawl in Allston",
  "Thrift Store Treasure Hunt",
  "Street Art Hunt in Roxbury",
  "Live Music Night in Cambridge",
  "Farmers Market Morning",
  "Brunch Crawl in South End",
  "Boston Harbor Walk",
  "Seaport Sunset Sit",
  "North End Pizza Tour",
  "Boston Tea Party Site Visit",
  "Freedom Trail Walk",
  "Hidden Speakeasy Hunt",
  "Public Library Study Day",
  "Board Game Cafe Night",
  "Dessert Crawl in Back Bay",
  "Brookline Cafe Day",
  "Allston Karaoke Night",
  "Fenway Bar Hop",
  "MIT Bridge Walk",
  "Charles River Kayak Day",
  "Boston Harbor Ferry Ride",
  "Art Gallery Hop",
  "Indie Bookstore Day",
  "Vintage Market Hunt",
  "Coffee + Journal Day",
  "Solo Date in Beacon Hill",
  "Boston Skyline Photo Walk",
  "Sunrise at Castle Island",
  "Seaport Rooftop Visit",
  "Hidden Park Discovery",
  "Boston Duck Tour Ride",
  "Chinatown Bubble Tea Crawl",
  "Late Night Pizza Run",
  "Boston Food Hall Sampling",
  "Local Bakery Crawl",
  "Outdoor Movie Night",
  "Boston Harbor Picnic",
  "Winter Snow Walk",
  "Fall Foliage Walk",
  "Spring Blossom Hunt",
  "Summer Ice Cream Day",
  "Boston Marathon Watch Day",
  "TD Garden Event Night",
  "Harborwalk Exploration",
  "North End Espresso Crawl",
  "Boston Skyline Night Walk",
  "Cambridge Poetry Night",
  "Jazz Night in Boston",
  "Open Mic Night",
  "Trivia Night at Local Bar",
  "Somerville Flea Market Day",
  "Cambridge Farmers Market",
  "Boston Brewery Tour",
  "Local Food Festival Day",
  "Street Performer Watch Day",
  "Boston Aquarium Visit",
  "Science Museum Day",
  "Isabella Stewart Gardner Visit",
  "Boston Harbor Cruise",
  "MIT Museum Visit",
  "Harvard Museum Tour",
  "Boston Tea Room Visit",
  "Seaport Yoga Day",
  "Charles River Run",
  "Boston Bike Ride Day",
  "Kayak + Picnic Combo",
  "Beach Day at Carson Beach",
  "Castle Island Food Run",
  "Boston Lighthouse Trip",
  "Sunset Ferry Ride",
  "Boston Food Truck Crawl",
  "Neighborhood Exploration Day",
  "Try a New Cuisine Day",
  "Street Food Sampling",
  "Dessert + Walk Combo",
  "Late Night Dessert Run",
  "Coffee Shop Work Day",
  "Study in a New Spot",
  "Boston Library Crawl",
  "Explore Hidden Alleys",
  "Boston Skyline Sketch Day",
  "Urban Photography Challenge",
  "Try 3 New Cafes",
  "Try 3 New Bakeries",
  "Try 3 New Restaurants",
  "Explore New Neighborhood",
  "Random T Stop Adventure",
  "Green Line Exploration",
  "Red Line Exploration",
  "Blue Line Adventure",
  "Orange Line Day",
  "Visit Every T Line Stop",
  "Boston Food Bucket List",
  "Iconic Boston Landmarks Tour",
  "Boston History Walk",
  "Freedom Trail at Night",
  "Boston Ghost Walk",
  "Explore Old Cemeteries",
  "Boston Hidden History Day",
  "Local Artist Gallery Visit",
  "DIY Art Day in Park",
  "Sketch Boston Architecture",
  "Film Photo Walk",
  "Boston Night Photography",
  "Street Portrait Day",
  "Food Photography Challenge",
  "Cafe Hopping with Friends",
  "Solo Cafe Reflection Day",
  "Boston Chill Day",
  "Digital Detox Walk",
  "No Phone Exploration Day",
  "Mindful Walk in Boston",
  "Boston Wellness Day",
  "Try Yoga Studio",
  "Meditation by Charles River",
  "Boston Spa Day",
  "Try New Workout Class",
  "Run Across Bridges",
  "Explore Boston Bridges",
  "Boston Staircase Hunt",
  "Hill Climb Challenge",
  "Walk 20K Steps in Boston",
  "Boston Marathon Route Walk",
  "Visit All Boston Parks",
  "Explore Public Gardens",
  "Boston Picnic Marathon",
  "Eat Only Local for a Day",
  "Support Small Businesses Day",
  "Local Coffee Loyalty Day",
  "Try Boston Food Trends",
  "Try Viral Boston Spots",
  "Hidden Gem Restaurant Hunt",
  "Budget Eats Challenge",
  "Luxury Dining Day",
  "Boston Date Night Plan",
  "Friend Hangout Day",
  "Group Challenge Day",
  "Weekend Boston Adventure",
  "Rainy Day Cafe Crawl",
  "Snow Day Exploration",
  "Heatwave Ice Cream Crawl",
  "Boston Night Adventure",
  "Midnight Walk Challenge",
  "Sunrise to Sunset Day",
  "Boston Bucket List Day",
  "Explore Like a Tourist",
  "Act Like a Local Day",
  "Try Something New Day",
  "Comfort Zone Break Day",
  "Say Yes Day in Boston",
  "Random Yelp Pick Day",
  "Let Friends Decide Day",
  "Spin the Map Challenge",
  "Pick a Random Neighborhood",
  "Try a New Hobby Day",
  "Boston Creative Day",
  "DIY Content Creation Day",
  "Vlog Your Boston Day",
  "Photo Dump Challenge",
  "Instagram Reel Day",
  "Aesthetic Cafe Tour",
  "Boston Minimalist Day",
  "Maximalist Exploration Day",
  "Boston Fashion Day",
  "Thrift Fit Challenge",
  "Vintage Outfit Day",
  "Boston Street Style Hunt",
  "Find Cool Murals",
  "Find Hidden Corners",
  "Explore Side Streets",
  "Boston Secret Spots",
  "Local Recommendations Day",
  "Ask Strangers for Suggestions",
  "Community Event Day",
  "Volunteer in Boston",
  "Give Back Day",
  "Boston Kindness Challenge",
  "Talk to 5 New People",
  "Make a New Friend Day",
  "Boston Social Challenge",
  "Introvert Adventure Day",
  "Extrovert Energy Day",
  "Boston Reset Day",
  "Mental Health Walk",
  "Reflection Day by Water",
  "Journal in 3 Locations",
  "Boston Gratitude Day",
  "Boston Solo Adventure",
  "Date Yourself Day",
  "Boston Exploration Marathon",
  "City Scavenger Hunt",
  "Boston Treasure Hunt",
  "Food + Walk Combo",
  "Walk + Coffee Combo",
  "Coffee + Dessert Combo",
  "Dessert + Sunset Combo",
  "Sunset + Walk Combo",
  "Walk + Music Combo",
  "Music + Night Walk",
  "Boston After Dark",
  "Late Night Boston Run",
  "Boston Night Eats",
  "Explore Boston Rooftops",
  "Boston Skyline Views Hunt",
  "Find Best Sunset Spot",
  "Find Best Sunrise Spot",
  "Boston Chill Spots Hunt",
  "Boston Cozy Spots Hunt",
  "Boston Quiet Spots Hunt",
  "Boston Study Spots Hunt",
  "Boston Work From Cafe Day",
  "Boston Remote Work Day",
  "Boston Creative Cafe Day",
  "Boston Writer Day",
  "Boston Artist Day",
  "Boston Explorer Mode",
  "Boston Adventure Mode",
  "Boston Foodie Mode",
  "Boston Chill Mode",
  "Boston Social Mode",
  "Boston Solo Mode",
  "Boston Nature Mode",
  "Boston Urban Mode",
  "Boston Culture Mode",
  "Boston History Mode",
  "Boston Luxury Mode",
  "Boston Budget Mode",
  "Boston Random Mode",
];

const neighborhoods = [
  "Allston",
  "Back Bay",
  "Bay Village",
  "Beacon Hill",
  "Brighton",
  "Charlestown",
  "Chinatown",
  "Dorchester",
  "Downtown",
  "East Boston",
  "Fenway",
  "Hyde Park",
  "Jamaica Plain",
  "Leather District",
  "Longwood",
  "Mattapan",
  "Mission Hill",
  "North End",
  "Roslindale",
  "Roxbury",
  "Seaport",
  "South Boston",
  "South End",
  "West End",
  "West Roxbury",
];

function generateChallenge(i) {
  const title = titles[Math.floor(Math.random() * titles.length)];
  const area = neighborhoods[Math.floor(Math.random() * neighborhoods.length)];

  return {
    title: `${area} ${title}`,
    description: `Experience a cozy ${title.toLowerCase()} in ${area}`,
    category: "explore",
    neighborhood: area,
    timeWindow: "weekend",
    createdBy: null,
    createdAt: new Date(),
    stats: { likes: 0, saves: 0, completions: 0 },
    steps: [
      { id: crypto.randomUUID(), title: "Explore first spot", points: 10 },
      { id: crypto.randomUUID(), title: "Capture a moment", points: 15 },
      { id: crypto.randomUUID(), title: "Reflect or rate", points: 10 },
    ],
  };
}

router.post("/", async (req, res) => {
  const db = req.app.locals.db;

  const challenges = Array.from({ length: 1000 }, (_, i) =>
    generateChallenge(i)
  );

  await db.collection("challenges").deleteMany({});

  const result = await db.collection("challenges").insertMany(challenges);

  res.json({
    message: "1000 themed challenges inserted",
    count: result.insertedCount,
  });
});

export default router;
